# Generated by Django 4.1.13 on 2024-07-26 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('government_id', models.CharField(max_length=20)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debt_due_date', models.DateField()),
                ('debt_id', models.UUIDField()),
                ('sended', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('government_id', 'email', 'debt_id')},
            },
        ),
    ]
