version: '3'

services:
  db:
    container_name: postgres_container_billing
    image: postgres
    environment:
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_pass
      POSTGRES_DB: billing_db
    networks:
      - backend_network
    ports:
      - "5432:5432"
  web:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    command: >
      sh -c " python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=billing_db
      - DATABASE_PORT=5432
      - DATABASE_USER=billing_user
      - DATABASE_PASSWORD=billing_pass
    networks:
      - backend_network

volumes:
  postgres_data:


networks:
  backend_network:
    driver: bridge
